import Navbar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/sessionprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" className="h-full">
      <body className={`h-full ${inter.className} bg-blue-900 text-white`}>
        <SessionProvider session={session}>
          <div className="flex flex-col h-full">
            <Navbar />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}